### 
GET http://localhost:3000/

###

### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "123"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "123"
}